import { useState, type FormEvent, type KeyboardEvent } from 'react'
import { ArrowUp, Paperclip } from 'lucide-react'

import { Button } from '@/components/ui/button'

type ChatComposerProps = {
  disabled?: boolean
  isBusy: boolean
  onSend: (text: string) => void
  placeholder?: string
}

function ChatComposer({
  disabled = false,
  isBusy,
  onSend,
  placeholder = 'Ask Slash anything',
}: ChatComposerProps) {
  const [input, setInput] = useState('')
  const canSend = input.trim().length > 0 && !isBusy && !disabled

  function sendMessage() {
    const message = input.trim()

    if (!message || isBusy || disabled) {
      return
    }

    setInput('')
    onSend(message)
  }

  function handleSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault()
    sendMessage()
  }

  function handleKeyDown(event: KeyboardEvent<HTMLTextAreaElement>) {
    if (event.key === 'Enter' && !event.shiftKey) {
      event.preventDefault()
      sendMessage()
    }
  }

  return (
    <div className="bg-gradient-to-t from-background via-background to-transparent px-4 pt-4 pb-5 sm:px-8">
      <form
        onSubmit={handleSubmit}
        className="mx-auto max-w-3xl rounded-2xl border bg-card p-2 shadow-[0_8px_30px_rgb(0_0_0/0.07)] transition-shadow focus-within:shadow-[0_10px_36px_rgb(0_0_0/0.1)]"
      >
        <textarea
          value={input}
          rows={1}
          aria-label="Message Slash"
          disabled={disabled}
          placeholder={placeholder}
          className="max-h-36 min-h-12 w-full resize-none bg-transparent px-3 py-3 text-[15px] leading-6 outline-none placeholder:text-muted-foreground/70 [field-sizing:content]"
          onChange={(event) => setInput(event.target.value)}
          onKeyDown={handleKeyDown}
        />
        <div className="flex items-center justify-between px-1 pb-1">
          <Button
            type="button"
            variant="ghost"
            size="icon-sm"
            aria-label="Attach a file"
            disabled
          >
            <Paperclip />
          </Button>
          <Button
            type="submit"
            size="icon-sm"
            aria-label="Send message"
            disabled={!canSend}
            className="rounded-lg"
          >
            <ArrowUp />
          </Button>
        </div>
      </form>
      <p className="mx-auto mt-2.5 max-w-3xl text-center text-[11px] text-muted-foreground">
        Responses are generated by your configured provider and may be inaccurate.
      </p>
    </div>
  )
}

export { ChatComposer }
